services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: backend
    container_name: backend
    env_file:
      - .env
    ports:
      - '${BACKEND_PORT}'
    volumes:
      - ./backend:/app/backend # Mount backend source code
      - ./shared:/app/shared # Mount shared source code
      - uploads:/app/backend/database/uploads # user avatars
      - pnpm_store:/root/.local/share/pnpm/store # pnpm store
      - /app/backend/node_modules # Preserve node_modules
      - /app/backend/services/main_server/node_modules
      - /app/backend/services/game_service/node_modules
      - /app/backend/services/matchmaking_service/node_modules
      - /app/backend/services/user_service/node_modules
      - /app/backend/services/remote_service/node_modules

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - '${FRONTEND_PORT}' # Vite default port
    volumes:
      - ./frontend:/app/frontend # Mount frontend source code
      - ./shared:/app/shared # Mount shared source code
      - pnpm_store:/root/.local/share/pnpm/store # pnpm store
      - /app/frontend/node_modules # Preserve node_modules

  nginx:
    build: ./nginx
    image: nginx:pong
    container_name: nginx
    ports:
      - '8443:8443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - uploads:/app/backend/database/uploads
    depends_on:
      - frontend
      - backend

volumes:
  uploads:
  pnpm_store:
